name: CI

on:
  push:
    branches: [homolog]
  pull_request:
    branches: [main]

jobs:
  sonarQube:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
